# Generated by Django 5.2.7 on 2025-10-30 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortcutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('set_type', models.CharField(choices=[('general', 'General (Birou)'), ('personal', 'Personal (Utilizator)')], default='general', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shortcut Set',
                'verbose_name_plural': 'Shortcut Sets',
                'ordering': ['set_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='shortcut',
            options={'ordering': ['key'], 'verbose_name': 'Shortcut', 'verbose_name_plural': 'Shortcuts'},
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='shortcuts', to='textsync.shortcutset'),
        ),
    ]
