# Generated by Django 5.2.7 on 2025-12-22 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textsync", "0004_shortcut_content_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortcutUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain where the shortcut was used",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shortcut Usage Log",
                "verbose_name_plural": "Shortcut Usage Logs",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AddField(
            model_name="shortcut",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time this shortcut was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this shortcut. Staff can only see/edit their own shortcuts.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_shortcuts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total times this shortcut has been expanded"
            ),
        ),
        migrations.AddField(
            model_name="shortcutset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this set. Staff can only see/edit their own sets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_sets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shortcutset",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff users who can see this set (in addition to the owner). Only superusers can set this.",
                related_name="visible_sets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_shortcuts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="value",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="shortcut",
            index=models.Index(fields=["key"], name="textsync_sh_key_10c937_idx"),
        ),
        migrations.AddIndex(
            model_name="shortcut",
            index=models.Index(
                fields=["updated_at"], name="textsync_sh_updated_9b3083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortcut",
            index=models.Index(
                fields=["usage_count"], name="textsync_sh_usage_c_903717_idx"
            ),
        ),
        migrations.AddField(
            model_name="shortcutusagelog",
            name="shortcut",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to="textsync.shortcut",
            ),
        ),
        migrations.AddField(
            model_name="shortcutusagelog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shortcut_usage_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="shortcutusagelog",
            index=models.Index(
                fields=["used_at"], name="textsync_sh_used_at_44e5d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortcutusagelog",
            index=models.Index(
                fields=["user", "used_at"], name="textsync_sh_user_id_3c5c5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortcutusagelog",
            index=models.Index(
                fields=["shortcut", "used_at"], name="textsync_sh_shortcu_2baf41_idx"
            ),
        ),
    ]
