# Generated by Django 5.2.7 on 2025-10-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsync', '0004_alter_shortcut_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='content_type',
            field=models.CharField(choices=[('text', 'Plain Text'), ('html', 'Rich Text (HTML)')], default='text', max_length=10),
        ),
    ]
