# Generated by Django 5.2.7 on 2026-04-25 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsync', '0005_add_usage_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shortcut',
            index=models.Index(fields=['updated_at', 'id'], name='textsync_sh_updated_bf3500_idx'),
        ),
    ]
