# Generated by Django 5.2.7 on 2026-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsync', '0009_shortcutalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Alternative bodies for random pick at expand time. Max 3.'),
        ),
    ]
