# Generated by Django 5.2.7 on 2026-04-30 12:41

from django.db import migrations, models


def revoke_all_tokens(apps, schema_editor):
    """Drop every existing ExpiringToken row.

    The schema flip stores SHA-256 hashes in `key` instead of plain
    tokens. Anything written before this migration is plain text that
    would no longer authenticate (the new auth backend hashes incoming
    keys before lookup). Deleting rows up front makes the contract
    explicit and avoids leaving plain-text values sitting in the DB
    even briefly.
    """
    ExpiringToken = apps.get_model("textsync", "ExpiringToken")
    ExpiringToken.objects.all().delete()


def noop_reverse(apps, schema_editor):
    """Reversal cannot recover plain tokens — there's nothing to do."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("textsync", "0010_shortcut_variants"),
    ]

    operations = [
        # Run BEFORE the AlterField so we never have a moment where the
        # column is widened but plain values still live alongside hashes.
        migrations.RunPython(revoke_all_tokens, noop_reverse),
        migrations.AlterField(
            model_name="expiringtoken",
            name="key",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
