"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

# Detect Django's test runner so prod-only hardening (HTTPS redirect, HSTS,
# secure cookies) doesn't kick in for `manage.py test` when DEBUG=False.
TESTING = "test" in sys.argv or "pytest" in sys.argv[0]

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# `DJANGO_SECRET_KEY` is mandatory in any environment; the dev fallback
# is only honoured when `DEBUG=True` AND the env var is missing, which
# keeps `manage.py runserver` working out-of-the-box without ever
# leaking the placeholder into production.
DEBUG = os.getenv("DEBUG", "False") == "True"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-secret-key-change-in-production"
    else:
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be set when DEBUG=False. "
            "Generate one with `python -c 'import secrets; print(secrets.token_urlsafe(64))'`."
        )

# Conditional ALLOWED_HOSTS based on DEBUG mode
if DEBUG:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS_DEBUG", "localhost,127.0.0.1").split(",")
else:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS_PROD", "autotext.zua.ro").split(",")

# Security Settings for Production
if not DEBUG and not TESTING:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    # Trust X-Forwarded-Proto header from nginx reverse proxy
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # HSTS Settings - tells browsers to only use HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Session/CSRF cookies only over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # SameSite cookies for CSRF protection
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    # Prevent browsers from guessing content type
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Enable XSS filter in browsers
    SECURE_BROWSER_XSS_FILTER = True
    # Don't allow site to be framed (clickjacking protection)
    X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    "tinymce",
    # Local
    "textsync",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "textsync.middleware.RequestLoggingMiddleware",  # Structured logging context
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# django-silk — dev-only profiling. Opt-in via env (ENABLE_SILK=True) so tests
# stay fast and clean. Access at /silk/ after `uv run python manage.py migrate`.
if os.getenv("ENABLE_SILK", "False") == "True":
    try:
        import silk  # noqa: F401

        INSTALLED_APPS += ["silk"]
        MIDDLEWARE = ["silk.middleware.SilkyMiddleware"] + MIDDLEWARE
        SILKY_PYTHON_PROFILER = True
        SILKY_AUTHENTICATION = False
        SILKY_AUTHORISATION = False
    except ImportError:
        pass

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            # Connection-level lock-wait — complements PRAGMA busy_timeout (engine-level)
            # to absorb short contention from concurrent writes under WAL mode.
            "timeout": 20,
        },
    }
}


# Cache Configuration
# Redis cache for shortcuts and API responses
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "IGNORE_EXCEPTIONS": True,  # Graceful degradation if Redis unavailable
        },
        "KEY_PREFIX": "autotext",
        "TIMEOUT": 300,  # 5 minutes default cache timeout
    }
}

# Cache timeouts (named constants preferred for new code; dict kept for legacy .get() lookups)
CACHE_TTL_SHORTCUTS = 60 * 5  # 5 minutes
CACHE_TTL_SHORTCUT_SETS = 60 * 10  # 10 minutes
CACHE_TTL_USER_DATA = 60 * 2  # 2 minutes

CACHE_TIMEOUTS = {
    "shortcuts": CACHE_TTL_SHORTCUTS,
    "shortcut_sets": CACHE_TTL_SHORTCUT_SETS,
    "user_data": CACHE_TTL_USER_DATA,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# CORS Configuration
#
# Browser-extension content scripts run with the *host page* as the request
# origin (mail.google.com, outlook.live.com, etc.), not the extension's
# chrome-extension:// origin. So while we keep CORS_ALLOWED_ORIGINS for
# direct calls (admin, dashboard), we also accept any origin that hits the
# `/api/*` namespace via CORS_URLS_REGEX + CORS_ALLOWED_ORIGIN_REGEXES.
#
# Auth still gates everything (DRF Token in Authorization header, no
# session cookies on /api/), so opening up the CORS preflight surface here
# does not weaken access control — a request without a valid token still
# returns 401, regardless of origin.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://autotext.zua.ro",
    "http://localhost:8000",  # local development
    "http://127.0.0.1:8000",  # local development
]
# Apply CORS only to /api/ — admin pages stay strict-origin.
CORS_URLS_REGEX = r"^/api/.*$"
# Match any HTTPS or chrome-extension origin for /api/ calls. Token auth
# is the real gate.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.+$",
    r"^chrome-extension://.+$",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "textsync.authentication.ExpiringTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Anonymous users
        "anon": "100/hour",
        # Authenticated users - general API
        "user": "1000/hour",
        # Specific endpoints with stricter limits
        "login": "10/minute",  # Prevent brute force
        "token_refresh": "5/hour",  # Prevent token churn
        "bulk_sync": "60/hour",  # Heavy operation
    },
}

# Application Version (used in health checks)
APP_VERSION = os.getenv("APP_VERSION", "1.0.0")

# =============================================================================
# Structured Logging with structlog
# =============================================================================
import structlog  # noqa: E402 - must be after DEBUG is defined

# Shared processors used by both structlog and standard logging
shared_processors = [
    structlog.contextvars.merge_contextvars,  # Merge context from contextvars
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.UnicodeDecoder(),
]

# In development, use console renderer for readability
# In production, use JSON renderer for log aggregation
if DEBUG:
    # Pretty console output for development
    final_processors = [
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]
    console_formatter = "colored"
else:
    # JSON output for production (ELK, Datadog, etc.)
    final_processors = [
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]
    console_formatter = "json"

# Configure structlog
# mypy widens the concatenation `shared_processors + final_processors` to
# `list[object]`; structlog's Processor protocol is a callable, not a base
# class, so the runtime contract holds even when the static type does not.
structlog.configure(
    processors=shared_processors + final_processors,  # type: ignore[arg-type]
    wrapper_class=structlog.stdlib.BoundLogger,
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

# Logging Configuration (Django + structlog)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
            "foreign_pre_chain": shared_processors,
        },
        "colored": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(colors=True),
            "foreign_pre_chain": shared_processors,
        },
        "plain": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(colors=False),
            "foreign_pre_chain": shared_processors,
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": console_formatter,
        },
        "file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django.log",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "plain",
        },
        "security_file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "security.log",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "json",  # Security logs always in JSON for auditing
        },
        "json_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "app.json.log",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 10,
            "formatter": "json",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "json_file"] if not DEBUG else ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["security_file", "console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "textsync": {
            "handlers": ["console", "json_file"] if not DEBUG else ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    "height": "400px",
    "width": "100%",
    "menubar": "file edit view insert format tools table",
    "plugins": "advlist autolink lists link image charmap preview anchor "
    "searchreplace visualblocks code fullscreen "
    "insertdatetime media table paste code help wordcount",
    "toolbar": "undo redo | bold italic underline strikethrough | "
    "fontselect fontsizeselect formatselect | alignleft aligncenter "
    "alignright alignjustify | outdent indent | numlist bullist | "
    "forecolor backcolor removeformat | pagebreak | charmap emoticons | "
    "fullscreen preview save print | insertfile image media template link anchor "
    "codesample | ltr rtl",
    "toolbar_mode": "sliding",
    "contextmenu": "link image table",
    "content_css": "default",
    "branding": False,
    "promotion": False,
}
